services:
  mysql:
    build: ./docker/mysql
    container_name: mysql-container
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dev
      MYSQL_USER: dev
      MYSQL_PASSWORD: 123
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
      - ./backups:/backups # Каталог для бэкапов

  minio:
    image: bitnami/minio:latest
    container_name: minio
    restart: always
    environment:
      MINIO_DEFAULT_BUCKETS: backup:public
    ports:
      - "9000:9000"  # API MinIO
      - "9001:9001"  # Web-интерфейс MinIO
    volumes:
      - minio_data:/data

volumes:
  minio_data: