CREATE DATABASE IF NOT EXISTS `dev`;
CREATE DATABASE IF NOT EXISTS `dev_test`;

CREATE USER IF NOT EXISTS 'dev'@'%' IDENTIFIED BY '123';

GRANT PROCESS ON *.* TO 'dev'@'%'; FLUSH PRIVILEGES;
FLUSH PRIVILEGES;
